spring:
  application:
    name: bookshop-test
  profiles:
    active: default
  config:
    import: optional:configserver:http://localhost:9001/ # Connect to config server, in docker compose we should not
    #use this config server or left it with optional:, otherwise it will not work

server:
  port: 8080



