global:
  scrape_interval: 5m
  evaluation_interval: 5m

scrape_configs:
  - job_name: 'books'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ 'books:8081' ]

  - job_name: 'test'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ 'test:8080' ]

  - job_name: 'gateway'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ 'bookshop-gateway:8084' ]

#  - job_name: 'user'
#    metrics_path: /actuator/prometheus
#    static_configs:
#      - targets: [ 'user:8083' ]

  - job_name: 'config'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ 'config:9001' ]

  - job_name: 'barbershop-eureka'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ 'eureka:8085' ]

#  - job_name: 'order'
#    metrics_path: /actuator/prometheus
#    static_configs:
#      - targets: [ 'order:8082' ]
