apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookshop-book
  labels:
    app: bookshop-book
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookshop-book
  template:
    metadata:
      name: bookshop-book
      labels:
        app: bookshop-book
    spec:
      containers:
        - name: bookshop-book
          image: bookshop/bookshop-book:v8
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_APP_NAME
              valueFrom:
                configMapKeyRef:
                  name: bookshop-config
                  key: BOOKS_APPLICATION_NAME
            - name: SPRING_CONFIG_IMPORT
              valueFrom:
                configMapKeyRef:
                  name: bookshop-config
                  key: SPRING_CONFIG_IMPORT
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              valueFrom:
                configMapKeyRef:
                  name: bookshop-config
                  key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: bookshop-config
                  key: SPRING_DATASOURCE_URL
            - name: SPRING_LIQUIBASE_URL
              valueFrom:
                configMapKeyRef:
                  name: bookshop-config
                  key: SPRING_LIQUIBASE_URL
            - name: SPRING_LIQUIBASE_USER
              valueFrom:
                configMapKeyRef:
                  name: bookshop-config
                  key: SPRING_LIQUIBASE_USER
            - name: SPRING_LIQUIBASE_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: bookshop-config
                  key: SPRING_LIQUIBASE_PASSWORD

---
apiVersion: v1
kind: Service
metadata:
  name: bookshop-book
  labels:
    app: bookshop-book
spec:
  selector:
    app: bookshop-book
  type: LoadBalancer
  ports:
    - name: http
      port: 8081
      protocol: TCP
      targetPort: 8081
