apiVersion: apps/v1
kind: Deployment
metadata:
  name: config
  labels:
    app: config
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config
  template:
    metadata:
      labels:
        app: config
    spec:
      containers:
        - name: config
          image: bookshop/bookshop-config:v8
          ports:
            - containerPort: 9001
---
apiVersion: v1
kind: Service
metadata:
  name: config
spec:
  selector:
    app: config
  type:  LoadBalancer
  ports:
    - protocol: TCP
      port: 9001
      targetPort: 9001

