apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka
  labels:
    app: eureka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka
  template:
    metadata:
      name: eureka
      labels:
        app: eureka
    spec:
      containers:
        - name: eureka
          image: bookshop/eurekaserver:v8
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8085
          env:
            - name: SPRING_APP_NAME
              valueFrom:
                configMapKeyRef:
                  name: bookshop-config
                  key: EUREKA_APPLICATION_NAME
            - name: SPRING_CONFIG_IMPORT
              valueFrom:
                configMapKeyRef:
                  name: bookshop-config
                  key: SPRING_CONFIG_IMPORT

---
apiVersion: v1
kind: Service
metadata:
  name: eureka
  labels:
    app: eureka
spec:
  selector:
    app: eureka
  type: LoadBalancer
  ports:
    - name: http
      port: 8085
      protocol: TCP
      targetPort: 8085