apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookshop-gateway
  labels:
    app: bookshop-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookshop-gateway
  template:
    metadata:
      name: bookshop-gateway
      labels:
        app: bookshop-gateway
    spec:
      containers:
        - name: bookshop-gateway
          image: bookshop/bookshop-gateway:v8
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8084
          env:
            - name: SPRING_APP_NAME
              valueFrom:
                configMapKeyRef:
                  name: bookshop-config
                  key: GATEWAY_APPLICATION_NAME
            - name: SPRING_CONFIG_IMPORT
              valueFrom:
                configMapKeyRef:
                  name: bookshop-config
                  key: SPRING_CONFIG_IMPORT
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              valueFrom:
                configMapKeyRef:
                  name: bookshop-config
                  key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE

---
apiVersion: v1
kind: Service
metadata:
  name: bookshop-gateway
  labels:
    app: bookshop-gateway
spec:
  selector:
    app: bookshop-gateway
  type: LoadBalancer
  ports:
    - name: http
      port: 8084
      protocol: TCP
      targetPort: 8084
      