apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookshop-test
  labels:
    app: bookshop-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookshop-test
  template:
    metadata:
      name: bookshop-test
      labels:
        app: bookshop-test
    spec:
      containers:
        - name: bookshop-test
          image: bookshop/bookshop-test:v8
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: bookshop-config
                  key: SPRING_PROFILES_ACTIVE
            - name: SPRING_APP_NAME
              valueFrom:
                configMapKeyRef:
                  name: bookshop-config
                  key: TEST_APPLICATION_NAME
            - name: SPRING_CONFIG_IMPORT
              valueFrom:
                configMapKeyRef:
                  name: bookshop-config
                  key: SPRING_CONFIG_IMPORT
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              valueFrom:
                configMapKeyRef:
                  name: bookshop-config
                  key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: bookshop-config
                  key: SPRING_DATASOURCE_URL
            - name: SPRING_LIQUIBASE_URL
              valueFrom:
                configMapKeyRef:
                  name: bookshop-config
                  key: SPRING_LIQUIBASE_URL
            - name: SPRING_LIQUIBASE_USER
              valueFrom:
                configMapKeyRef:
                  name: bookshop-config
                  key: SPRING_LIQUIBASE_USER
            - name: SPRING_LIQUIBASE_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: bookshop-config
                  key: SPRING_LIQUIBASE_PASSWORD

---
apiVersion: v1
kind: Service
metadata:
  name: bookshop-test
  labels:
    app: bookshop-test
spec:
  selector:
    app: bookshop-test
  type: LoadBalancer
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
      