spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres # ???????? ?? ??? URL
    username: postgres  # ???????? ?? ??? username
    password: mysecretpassword  # ???????? ?? ??? ??????
    driver-class-name: org.postgresql.Driver
    jpa:
      hibernate:
        ddl-auto: update  # ??????????? "none", "update", "create", ??? "create-drop" ? ??????????? ?? ????? ????
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      show-sql: true      # ??? ?????? SQL ???????? ? ???
      properties:
        hibernate:
          format_sql: true
    hikari:
      schema: bookshop
  liquibase:
    enabled: false

logging:
  level:
    com:
      libra:
        bookshopuser: DEBUG
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"

server:
  port: 8082
  servlet:
    session:
      timeout: ${SESSION_TIMEOUT:2m}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8085/eureka/ # URL Eureka Server
    fetch-registry: true   # Получать информацию о других сервисах (по умолчанию true)
    register-with-eureka: true # Регистрироваться на сервере Eureka (по умолчанию true)
  instance:
    prefer-ip-address: true # Использовать IP-адрес вместо hostname
    instance-id: ${spring.application.name}:${spring.cloud.client.hostname}:${server.port}

management:
  endpoints:
    web:
      exposure:
        include: "*" # expose all endpoints(refresh,health,info...)
  health:
    livenessstate:
      enabled: true
    readystatestate:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
    shutdown:
      enabled: true
    info:
      enabled: true
    metrics:
      tags:
        application: ${spring.application.name}

endpoints:
  shutdown:
    enabled: true